# Generated by Django 4.2.6 on 2023-11-26 04:37

import SAORA.apps.entidad.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TipoContacto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tipo_contacto", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.CharField(max_length=250)),
                (
                    "ultima_actualizacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoEntidad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tipo_entidad", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.CharField(max_length=250)),
                (
                    "ultima_actualizacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entidad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "codigo_ent",
                    models.PositiveIntegerField(
                        default=SAORA.apps.entidad.models.random_string
                    ),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                ("dir_calle", models.CharField(max_length=50)),
                ("dir_numero", models.CharField(max_length=10)),
                ("dir_int", models.CharField(max_length=6)),
                ("dir_colonia", models.CharField(max_length=50)),
                ("dir_ciudad", models.CharField(max_length=50)),
                ("dir_estado", models.CharField(max_length=50)),
                ("dir_pais", models.CharField(max_length=25)),
                ("dir_cp", models.CharField(max_length=10)),
                ("representante", models.CharField(max_length=50)),
                ("mision", models.CharField(max_length=500)),
                (
                    "tipo_entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="entidad.tipoentidad",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("nombre_contacto", models.CharField(max_length=50)),
                ("contacto", models.CharField(max_length=50)),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="entidad.entidad",
                    ),
                ),
                (
                    "tipo_contacto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="entidad.tipocontacto",
                    ),
                ),
            ],
        ),
    ]
