# Generated by Django 4.2.6 on 2023-10-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="activo",
        ),
    ]
